# Generated by Django 5.0.2 on 2024-04-29 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_date',
            field=models.DateField(default=datetime.date(2024, 4, 29)),
        ),
    ]
