# Generated by Django 5.0.2 on 2024-04-30 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_hour',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 15, 14, 4, 37738)),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_date',
            field=models.DateField(default=datetime.date(2024, 4, 30)),
        ),
    ]
