# Generated by Django 5.0.2 on 2024-04-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_posted_hour_alter_post_posted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_hour',
        ),
    ]
