# Generated by Django 5.0.2 on 2024-04-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_posted_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_hour_server',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
