# Generated by Django 5.0.2 on 2024-05-01 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_posted_hour_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_hour_client',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_date',
            field=models.DateField(default=datetime.date(2024, 5, 1)),
        ),
    ]
