# Generated by Django 5.0.2 on 2024-06-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_rename_likesmodel_likepost_comment_likecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_hour_client',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='posted_hour_server',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_hour_client',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_hour_server',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
