# Generated by Django 5.0.2 on 2024-06-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_post_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_hour_client',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_hour_server',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
