# Generated by Django 5.0.2 on 2024-06-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_post_posted_date_alter_post_posted_hour_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_hour_client',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted_hour_server',
        ),
    ]
