# Generated by Django 5.0.2 on 2024-06-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_remove_post_posted_hour_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='folllows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='blog.profile'),
        ),
    ]
