# Generated by Django 5.0.2 on 2024-06-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_profile_folllows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='folllows',
            new_name='follows',
        ),
    ]
