# Generated by Django 5.0.2 on 2024-08-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_post_comments_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
